### ISSUE TITLE
Vietnamese(vi) translation

### ISSUE THREAD

**Issue by nghiaxlee** [ncase/crowds#12]
I'm working on it.
If somebody wants to help, please let me know. xD

**Comment by NOVAglow** [comment]
I can help you.

**Comment by nghiaxlee** [comment]
https://github.com/nghiaxlee/crowds/vi.html
This is what I've done till now.

**Comment by MrN83** [comment]
Hi guys,

First of all, thank you for starting this translation work, I think the original work is excellent and must be made known to more Vietnamese speakers!

I had a quick look at a few pages you translated and found a few small issues. Would you mind if I fix them to improve the translation?

E.g. 

Example 1:
EN: As Mr. Newton later said: <i>“I can calculate the motion of heavenly bodies, but not the madness of people.”</i>

VN: Theo như Newton nói: <i>“Tôi có thể tính được chuyển động của một người trên thiên đàng, những không tính được sự điên cuồng của con người.”</i>

Imho, "chuyển động của một người trên thiên đàng" is incorrect translation. It should be "chuyển động của các vật thể trong vũ trụ" hoặc đơn giản hơn, "chuyển động của các tinh cầu".

Example 2:
EN: But people don't just passively <i>observe</i> others' ideas and behaviors, they actively <i>copy</i> them.

VN: Nhưng người ta không chỉ đứng đó <i>nhìn</i> ý tưởng và hành vi của người khác, họ chủ động <i>làm theo.</i>

Imho, "passively observe" should be more precisely translated as "quan sát một cách thụ động".
=======

I am a native Vietnamese speaker and have been doing a lot of translation work in my free time in addition to my main work as a maths and computer science teacher in Australia. I will only have enough time to scan through your translation and do spot fixes to iron out small mistakes and improve clarity where appropriate.

Since you are the original translators, I would like to ask for your opinion before commencing, out of respectful acknowledgement of your hard work.

I hope to hear from you soon.

Kind regards,

Tue Nguyen.

**Comment by NOVAglow** [comment]
Yes. I have to agree that there are lots of mistakes in the translation. I thought of fixing it but I don't have much time.

**Comment by NOVAglow** [comment]
Hi again! The fix is on me!

I haven't done it yet but I've made some progress. Here are a few changes I've made:

- Translate some English text preserved by the translator to Vietnamese
- Fix translation of the line " As Mr. Newton later said: “I can calculate the motion of heavenly bodies, but not the madness of people.” " per suggestion from @MrN83 
- Change "$4,600,000" to "$4.600.000"
- Fix this thing:

![](https://user-images.githubusercontent.com/24489228/42565454-ac3eecb8-852d-11e8-9e26-75c1ac6010f6.png)
![](https://user-images.githubusercontent.com/24489228/42565461-b0d27ef2-852d-11e8-86d2-38258d0121c4.png)

I have to do something else now but I will continue doing it in the evening.

**Comment by NOVAglow** [comment]
Okay, I finished fixing it. I didn't bother the text in the reference boxes. Maybe any of you do it for me?

If you want to have a review, please tell me before I throw the fixed one in.

**Comment by MrN83** [comment]
@NOVAglow, thanks for the work 👍. Please check in the changes and I'll continue the work when I have the time. 

Btw, please clarify "text in the references boxes" (perhaps with a screen shot) so I can address it. 

Thank you again everyone 🥇 !

**Comment by NOVAglow** [comment]
Well, in the game, there're little asterisks ('*') that, if you click on, a reference box pops up. I have not translated the text in those box. I have otherr stuff to do. Can you do it for me? Or can we just leave those boxes as-is, considering the fact that not too many people actually care about those boxes?

![example of a "reference box"](https://user-images.githubusercontent.com/24489228/42675462-61c5d27e-869e-11e8-97ac-08595160d0d6.png)

**Comment by MrN83** [comment]
Ah, I get it now. I do read those boxes :D. So I'll include them in my work when I get around to that. I'm going to check out the repository and create a new issue soon. Please make sure you've checked in your changes. 

Thanks for your contribution!

Cheers.

**Comment by NOVAglow** [comment]
@MrN83 So, how about, I create a fork of this repository, and then you commit to my fork?

**Comment by MrN83** [comment]
Actually, to keep things simple, you can just share your vi.html file with me (sending me a Dropbox etc. link to it will do) and I will merge it manually on my computer with my changes. Then I will commit the whole thing to the repo.

Hope to hear from you soon.

Cheers.
