### ISSUE TITLE
UX issue: After going into any of the translations, it's not obvious how to go back into English

### ISSUE THREAD

**Issue by AlexanderClay** [ncase/crowds#27]
I have "en: English" enabled in the translation.txt, yet it's not available on the dialog.

![sprite-0001](https://user-images.githubusercontent.com/32722574/39418754-3d87c556-4c2a-11e8-8791-046d39878425.png)

**Comment by AlexanderClay** [comment]
To be more clear, my issue is more like "how can I go back to the title card where I can select the English translation?"

**Comment by ncase** [comment]
...hm, that's actually a good point!  I'll add another link, next to "(add your own!)", saying "(original in English)".  That one probably won't have to be translated because, presumably, you read English if you want to read the game in English

Also thank you @AlexanderClay for translating so many of my interactives into Arabic, and thank you for putting up with my code weird-ness and my still not yet knowing how to make RTL easily supportable :P
